# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  runtimeConfiguration: 'win-x64'

steps:
- script: dotnet restore
  displayName: 'Restoring Project'

- task: DotNetCoreCLI@2
  displayName: 'Building Project'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --runtime $(runtimeConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: 'Testing'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'RestfulApiArtifact'
